name 'vogon'
maintainer 'Rob Lyon'
maintainer_email 'you@rlyon.me'
license 'MIT'
description 'Install and configure laptops and workstations'
long_description 'A bad-tempered, bureaucratic, officious and callous cookbook to tame workstations and laptops that on their own have as much sex appeal as a road accident.'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/rlyon/vogon/issues'
source_url 'https://github.com/rlyon/vogon'
